pets = [{
    image: "https://bit.ly/2zlujfS",
    name: "Dakota",
    color: "Golden",
    specialSkill: "Retrieving things!",
    type: "dog",
  },
  {
    image: "https://on.natgeo.com/2x2UJCk",
    name: "Teddy",
    color: "Brown",
    specialSkill: "Playing fetch!",
    type: "dog",
  },
  {
    image: "https://bit.ly/2S415sp",
    name: "Lola",
    color: "Black",
    specialSkill: "Fiercly loyal!",
    type: "dog",
  },
  {
    image: "https://bit.ly/2VvWwta",
    name: "Maggie",
    color: "Brown/White",
    specialSkill: "Lounging around!",
    type: "dog",
  },
  {
    image: "https://bit.ly/2VxGj6N",
    name: "Faye",
    color: "Gray",
    specialSkill: "Hiding, but very loveable!",
    type: "cat",
  },
  {
    image: "https://bit.ly/2Vx84Mx",
    name: "Cali",
    color: "Orange/Black",
    specialSkill: "Purrs and cuddles!",
    type: "cat",
  },
  {
    image: "https://bit.ly/2RZ0xnG",
    name: "Shadow",
    color: "Black",
    specialSkill: "Playing peek-a-boo from dark corners!",
    type: "cat",
  },
  {
    image: "https://bit.ly/2KwXwGZ",
    name: "Tyrannosaurus Rex",
    color: "Dark Green",
    specialSkill: "Eats all his meals; no wasted food!",
    type: "dino",
  },
  {
    image: "https://bit.ly/34YnnkI",
    name: "Brachiosaurus",
    color: "Light Brown",
    specialSkill: "Reaches all those hard-to-reach places!",
    type: "dino",
  },
  {
    image: "https://bit.ly/2zjzKMi",
    name: "Triceratops",
    color: "Dark Gray",
    specialSkill: "Great guard dino!",
    type: "dino",
  },
  {
    image: "https://bit.ly/2VyXfde",
    name: "Pterodactyl",
    color: "Exotic",
    specialSkill: "Can show you a whole new world!",
    type: "dino",
  }
];